#!/bin/bash
# shellcheck disable=SC1083

set -euo pipefail
exec 2>&1

function create_postgres_cluster() {

  echo PostgreSQL Cluster does not exist, creating with 'initdb'

  export RANDFILE="{{pkg.svc_var_path}}/.rnd"
  DB_PASSWORD="{{cfg.init.superuser_password}}"

  mkdir -p {{pkg.svc_config_path}}/conf.d
  mkdir -p {{pkg.svc_var_path}}/pg_stat_tmp

  chown -R hab:hab {{pkg.svc_var_path}}
  touch $RANDFILE

  if [ -z "${DB_PASSWORD}" ]; then
    openssl rand -base64 32 >{{pkg.svc_config_path}}/pwfile
  else
    echo "${DB_PASSWORD}" >{{pkg.svc_config_path}}/pwfile
  fi

  initdb \
    --username {{cfg.datastore.user}} \
    --encoding {{cfg.init.encoding}} \
    --pgdata {{pkg.svc_data_path}} \
    --pwfile {{pkg.svc_config_path}}/pwfile \
    --no-locale

  chmod 400 {{pkg.svc_config_path}}/pwfile
}

function create_builder_database() {
  # This call to postgres' createdb command depends on the various PG* envvars
  # but they have been "inlined" into "main". Also the createdb call used to
  # happen in the init of builder-api but ensure that the baseline DB is ready
  # for the rest of the system really feels like it lives here.
  createdb
}

function upgrade_needed() {

  # There is an argument to be made that this version check logic should
  # account for a 3 part version number instead of just a 2 part but starting
  # with PostgreSQL 10 the versioning scheme PostgreSQL versions are 2 parts.
  # We do have some 3 part 9.x.x PostgreSQL packages that we're possibly
  # migrating from but given that 9.6.24 has been EOL since Nov 11th 2021
  # hopefully no one has a reason to leverage those packages. Even if someone
  # did use the 9.x.x versions I think this will likely work acceptably and it
  #
  # https://www.postgresql.org/support/versioning/
  # https://endoflife.date/postgresql

  OIFS="$IFS"
  IFS='.'

  read -ra installed_version <<<"$(sudo cat /hab/svc/builder-datastore/data/PG_VERSION)"
  if [[ ! (${installed_version[0]} =~ [[:digit:]]+ && ${installed_version[1]} =~ [[:digit:]]+) ]]; then
    echo "Failed to parse the version of the installed PostgreSQL: We detected ${installed_version[*]}"
    exit 10
  fi

  read -ra packaged_version <<<"$(sudo hab pkg exec {{pkg.ident}} pg_config -- --version | awk '{print $2}')"
  if [[ ! (${packaged_version[0]} =~ [[:digit:]]+ && ${packaged_version[1]} =~ [[:digit:]]+) ]]; then
    echo "Failed to parse the version of the packaged PostgreSQL: We detected ${packaged_version[*]}"
    exit 11
  fi

  IFS="$OIFS"

  let retval=1
  if ((installed_version[0] < packaged_version[0])); then
    echo "PostgreSQL upgrade needed: ${installed_version[*]} < ${packaged_version[*]}"
    let retval=0
  else
    if ((installed_version[0] == packaged_version[0])); then
      if ((installed_version[1] < packaged_version[1])); then
        echo "PostgreSQL upgrade needed: ${installed_version[*]} < ${packaged_version[*]}"
        let retval=0
      fi
    fi
  fi

  return $retval
}

function get_installed_ident() {
  if ((${installed_version[0]} == 9)); then
    installed_ident=core/postgresql$(IFS='' echo "${packaged_version[*]:0:2}")
  else
    installed_ident=core/postgresql${packaged_version[0]}
  fi
}

function manage_readme() {
  local readme
  readme="$1/README.txt"
  if [[ ! -f "$readme" ]]; then
    cat <<-EOF >"$readme"
			This directory contains subdirectories used when upgrading PostgreSQL from
			one version to another. The subdirectories are named using the date and time
			of the upgrades. When you feel comfortable with the success of the upgrade
			you may delete these files.
		EOF
  fi
}

function upgrade_postgres() {

  echo Upgrading PostgreSQL

  local moment
  moment=$(date '+%Y%m%d%H%M%S')

  local work_dir
  work_dir="{{pkg.svc_var_path}}/tmp/upgrades/$moment"
  mkdir -p "$work_dir"

  manage_readme "$work_dir"

  local upgrade_log
  upgrade_log="$work_dir/upgrade.log"

  # Configure the environment such that we will be starting and stop postgres
  # with the binaries of the previous version of PostgreSQL.
  get_installed_ident
  eval "$(hab pkg env "${installed_ident}")"

  # pg_ctl start [-D datadir] [-l filename] [-W] [-t seconds] [-s] [-o options] [-p path] [-c]
  pg_ctl start -D {{pkg.svc_data_path}} -l "$upgrade_log"

  # https://dba.stackexchange.com/questions/264427/how-to-estimate-the-size-of-a-postgresql-db-to-be-dumped-through-pg-dump
  # Estimate available space

  # https://www.postgresql.org/docs/17/upgrading.html

  # STEP 1) Making a backup, making sure that your database is not being updated

  local pg_dump_file
  pg_dump_file="$work_dir/pg_dump.sql"
  hab pkg exec {{pkg.ident}} pg_dump >"$pg_dump_file"
  # "It is recommended that you use the pg_dump and pg_dumpall programs from the
  # newer version of PostgreSQL, to take advantage of enhancements that might
  # have been made in these programs. Current releases of the dump programs can
  # read data from any server version back to 9.2."
  #
  # https://www.postgresql.org/docs/17/upgrading.html#UPGRADING-VIA-PGDUMPALL

  # STEP 2) Shut down the old server

  pg_ctl stop

  # STEP 3) Rename the old installation directory

  local previous_dir
  previous_dir="$work_dir/previous"
  IFS='' mv "{{pkg.svc_data_path}}" "$previous_dir"

  # STEP 4) Install the new version of PostgreSQL (as outlined in Chapter 17)
  # This is a noop for us as our habitat package stands in

  # Restore the environment of the packaged PostgreSQL we're upgrading to
  eval "$(hab pkg env {{pkg.ident}})"

  # STEP 5) If needed, create a new database cluster. Remember you must be logged in as the special database user account
  create_postgres_cluster
  create_builder_database

  # STEP 6) Restore your previous pg_hba.conf and any postgresql.conf modifications
  # This is a noop for us as our hab svc layout manages this

  # STEP 7) Start the database server (again using the special database user account)
  pg_ctl start -D {{pkg.svc_data_path}} -l {{pkg.svc_path}}/logs/migration_"$moment".log

  # STEP 8) Finally, restore your data from backup
  command psql -d postgres -f "$pg_dump_file"

  # JAH: password upgrade would go here but would we even need it?
  # JAH: will this method of upgrade address it?
  # JAH: scram-sha-256 isn't supported until 10.x
}

#-------------------------------------------------------------------------------
# BEGIN "main"
#-------------------------------------------------------------------------------

if [[ -f "{{pkg.svc_data_path}}/PG_VERSION" ]]; then
  echo The PostgreSQL DB Cluster exists
else
  create_postgres_cluster
fi

# These env vars are needed by everything that follows
PGHOST="{{cfg.datastore.host}}"
PGPORT="{{cfg.datastore.port}}"
PGUSER="{{cfg.datastore.user}}"
PGPASSWORD="$(cat {{pkg.svc_config_path}}/pwfile)"
PGDATABASE="{{cfg.datastore.database}}"
export PGHOST PGPORT PGUSER PGPASSWORD PGDATABASE

if [[ $(command psql --no-password -c ";") ]]; then
  echo The builder database exists inside the PostgreSQL cluster
else
  create_builder_database
fi

if upgrade_needed; then
  upgrade_postgres
else
  echo PostgreSQL upgrade is not needed
fi

IFS="$OIFS"
