#!/bin/bash

exec 2>&1

chmod 0700 "{{pkg.svc_data_path}}"
export PGDATA="{{pkg.svc_data_path}}"

title="Service Start"
text="builder-datastore starting"
# shellcheck disable=SC2039,SC3025
echo "_e{${#title},${#text}}:$title|$text|#datastore" >/dev/udp/localhost/8125

# shellcheck disable=SC1083
exec postgres -c config_file={{pkg.svc_config_path}}/postgresql.conf
