#!/bin/sh
#

export PGDATA="{{pkg.svc_data_path}}"

exec 2>&1

chmod 0700 "{{pkg.svc_data_path}}"

# shellcheck disable=1083
exec {{pkgPathFor "core/postgresql"}}/bin/postmaster \
  -c config_file={{pkg.svc_config_path}}/postgresql.conf
