#!/bin/bash

export HOME="{{pkg.svc_data_path}}"
export RUST_LOG="{{cfg.log_level}}"
export RUST_BACKTRACE=1
export HAB_STUDIO_BACKLINE_PKG=core/hab-backline

# Wait for pem file before starting the service
while ! [ -f "{{pkg.svc_files_path}}/builder-github-app.pem" ];
do
    echo "Waiting for builder-github-app.pem"
    sleep 30
done

exec bldr-worker start -c "{{pkg.svc_config_path}}/config.toml" 2>&1
