#!/bin/bash

set -euo pipefail

PGHOST="{{cfg.datastore.host}}"
PGPORT="{{cfg.datastore.port}}"
PGUSER="{{cfg.datastore.user}}"
PGPASSWORD="{{cfg.datastore.password}}"
PGDATABASE="{{cfg.datastore.database}}"
export PGHOST PGPORT PGUSER PGPASSWORD PGDATABASE

# Check that the DB is exists and is reachable or create it
# NOTE: Builder's .studiorc has a psql function necessitating the use of command
if ! command psql --no-password --command=";"; then
  createdb
fi
