#!/bin/sh
set -e
export PGPASSWORD="{{cfg.datastore.password}}"
PSQL_ARGS="-w -h {{cfg.datastore.host}} -p {{cfg.datastore.port}} -U {{cfg.datastore.user}} {{cfg.datastore.database}}"
# shellcheck disable=SC2086
# Check that the DB exists or create it
psql -c ";" $PSQL_ARGS || createdb $PSQL_ARGS
