DROP FUNCTION IF EXISTS accept_origin_invitation_v1(bigint, boolean);
DROP FUNCTION IF EXISTS add_audit_package_entry_v1(bigint, bigint, bigint, smallint, smallint, bigint, text);
DROP FUNCTION IF EXISTS add_audit_package_group_entry_v1(bigint, bigint, bigint[], smallint, smallint, bigint, text, bigint);
DROP FUNCTION IF EXISTS check_account_in_origin_members_v1(text, bigint);
DROP FUNCTION IF EXISTS delete_origin_channel_v1(bigint);
DROP FUNCTION IF EXISTS delete_origin_integration_v1(text, text, text);
DROP FUNCTION IF EXISTS delete_origin_member_v1(bigint, text);
DROP FUNCTION IF EXISTS delete_origin_project_integration_v1(text, text, text);
DROP FUNCTION IF EXISTS delete_origin_project_v1(text);
DROP FUNCTION IF EXISTS delete_origin_secret_v1(bigint, text);
DROP FUNCTION IF EXISTS demote_origin_package_group_v1(bigint, bigint[]);
DROP FUNCTION IF EXISTS demote_origin_package_v1(bigint, bigint);
DROP FUNCTION IF EXISTS get_all_origin_packages_for_origin_v1(bigint);
DROP FUNCTION IF EXISTS get_origin_channel_package_latest_v5(text, text, text, text, text);
DROP FUNCTION IF EXISTS get_origin_channel_package_v4(text, text, text, text);
DROP FUNCTION IF EXISTS get_origin_channel_packages_for_channel_v3(text, text, text, text, bigint, bigint);
DROP FUNCTION IF EXISTS get_origin_channels_for_origin_v2(bigint, boolean);
DROP FUNCTION IF EXISTS get_origin_integration_v1(text, text, text);
DROP FUNCTION IF EXISTS get_origin_integrations_for_origin_v1(text);
DROP FUNCTION IF EXISTS get_origin_integrations_v1(text, text);
DROP FUNCTION IF EXISTS get_origin_invitation_v1(bigint);
DROP FUNCTION IF EXISTS get_origin_invitations_for_account_v1(bigint);
DROP FUNCTION IF EXISTS get_origin_invitations_for_origin_v1(bigint);
DROP FUNCTION IF EXISTS get_origin_package_channels_for_package_v4(text, text);
DROP FUNCTION IF EXISTS get_origin_package_latest_v5(text, text, text);
DROP FUNCTION IF EXISTS get_origin_package_platforms_for_package_v4(text, text);
DROP FUNCTION IF EXISTS get_origin_package_versions_for_origin_v7(text, text, text);
DROP FUNCTION IF EXISTS get_origin_packages_for_origin_distinct_v4(text, bigint, bigint, text);
DROP FUNCTION IF EXISTS get_origin_packages_for_origin_v5(text, bigint, bigint, text);
DROP FUNCTION IF EXISTS get_origin_packages_unique_for_origin_v4(text, bigint, bigint, text);
DROP FUNCTION IF EXISTS get_origin_private_encryption_key_v1(text);
DROP FUNCTION IF EXISTS get_origin_project_integrations_for_project_v2(text, text);
DROP FUNCTION IF EXISTS get_origin_project_integrations_v2(text, text, text);
DROP FUNCTION IF EXISTS get_origin_project_list_v2(text);
DROP FUNCTION IF EXISTS get_origin_project_v1(text);
DROP FUNCTION IF EXISTS get_origin_public_encryption_key_latest_v1(text);
DROP FUNCTION IF EXISTS get_origin_public_encryption_key_v1(text, text);
DROP FUNCTION IF EXISTS get_origin_public_encryption_keys_for_origin_v1(bigint);
DROP FUNCTION IF EXISTS get_origin_public_key_latest_v1(text);
DROP FUNCTION IF EXISTS get_origin_public_key_v1(text, text);
DROP FUNCTION IF EXISTS get_origin_public_keys_for_origin_v1(bigint);
DROP FUNCTION IF EXISTS get_origin_secret_key_v1(text);
DROP FUNCTION IF EXISTS get_origin_secret_v1(bigint, text);
DROP FUNCTION IF EXISTS get_origin_secrets_for_origin_v1(bigint);
DROP FUNCTION IF EXISTS ignore_origin_invitation_v1(bigint,  bigint);
DROP FUNCTION IF EXISTS insert_origin_integration_v1(text, text, text, text);
DROP FUNCTION IF EXISTS insert_origin_invitation_v1(bigint, text, bigint, text, bigint);
DROP FUNCTION IF EXISTS insert_origin_package_v3(bigint, bigint, text, text, text, text, text, text, text, text, text, text);
DROP FUNCTION IF EXISTS insert_origin_private_encryption_key_v1(bigint, bigint, text, text, text, bytea);
DROP FUNCTION IF EXISTS insert_origin_project_v5(text, text, text, text, text, bigint, bigint, text, boolean);
DROP FUNCTION IF EXISTS insert_origin_public_encryption_key_v1(bigint, bigint, text, text, text, bytea);
DROP FUNCTION IF EXISTS insert_origin_public_key_v1(bigint, bigint, text, text, text, bytea);
DROP FUNCTION IF EXISTS insert_origin_secret_key_v1(bigint, bigint, text, text, text, bytea);
DROP FUNCTION IF EXISTS insert_origin_secret_v1(bigint, text, text);
DROP FUNCTION IF EXISTS insert_origin_v2(text, bigint, text, text);
DROP FUNCTION IF EXISTS list_origin_by_account_id_v1(bigint);
DROP FUNCTION IF EXISTS list_origin_members_v1(bigint);
DROP FUNCTION IF EXISTS my_origins_v2(bigint);
DROP FUNCTION IF EXISTS promote_origin_package_group_v1(bigint, bigint[]);
DROP FUNCTION IF EXISTS rescind_origin_invitation_v1(bigint, bigint);
DROP FUNCTION IF EXISTS search_all_origin_packages_dynamic_v7(text, text);
DROP FUNCTION IF EXISTS search_all_origin_packages_v6(text, text);
DROP FUNCTION IF EXISTS search_origin_packages_for_origin_distinct_v1(text, text, bigint, bigint);
DROP FUNCTION IF EXISTS search_origin_packages_for_origin_v4(text, text, bigint, bigint, text);
DROP FUNCTION IF EXISTS set_packages_sync_v1(bigint);
DROP FUNCTION IF EXISTS sync_packages_v2();
DROP FUNCTION IF EXISTS update_origin_package_v1(bigint, bigint, text, text, text, text, text, text, text, text, text, text);
DROP FUNCTION IF EXISTS update_origin_project_v4(bigint, bigint, text, text, text, text, bigint, bigint, text, boolean);
DROP FUNCTION IF EXISTS update_origin_v1(bigint, text);
DROP FUNCTION IF EXISTS update_package_visibility_in_bulk_v1(text, bigint[]);
DROP FUNCTION IF EXISTS upsert_origin_integration_v1(text, text, text, text);
DROP FUNCTION IF EXISTS upsert_origin_project_integration_v3(text, text, text, text);
DROP FUNCTION IF EXISTS validate_origin_invitation_v1(bigint, bigint);
DROP FUNCTION IF EXISTS insert_origin_package_v4(bigint, bigint, text, text, text, text, text, text, text, text, text, text);
DROP FUNCTION IF EXISTS get_origin_channels_for_origin_v3(text, boolean);
DROP FUNCTION IF EXISTS delete_origin_channel_v2(text, text);
DROP FUNCTION IF EXISTS insert_origin_channel_v2(text, bigint, text);
DROP FUNCTION IF EXISTS add_audit_package_entry_v2(text, text, text, origin_package_operation, package_channel_trigger, bigint, text);
DROP FUNCTION IF EXISTS promote_origin_package_v2(text, text, text);
DROP FUNCTION IF EXISTS demote_origin_package_v2(text, text, text);
DROP FUNCTION IF EXISTS my_origins_with_stats_v1(bigint);
DROP FUNCTION IF EXISTS get_origin_channel_package_latest_v6(text, text, text, text, origin_package_visibility[]);
DROP FUNCTION IF EXISTS get_origin_channel_package_v5(text, text, text, origin_package_visibility[]);
DROP FUNCTION IF EXISTS get_origin_channel_packages_for_channel_v4(text, text, text, origin_package_visibility[], bigint, bigint);
DROP FUNCTION IF EXISTS get_origin_package_channels_for_package_v5(text, origin_package_visibility[]);
DROP FUNCTION IF EXISTS get_origin_package_latest_v6(text, text, origin_package_visibility[]);
DROP FUNCTION IF EXISTS get_origin_package_platforms_for_package_v5(text, origin_package_visibility[]);
DROP FUNCTION IF EXISTS get_origin_package_versions_for_origin_v8(text, text, origin_package_visibility[]);
DROP FUNCTION IF EXISTS get_origin_packages_for_origin_distinct_v5(text, bigint, bigint, origin_package_visibility[]);
DROP FUNCTION IF EXISTS get_origin_packages_for_origin_v6(text, bigint, bigint, origin_package_visibility[]);
DROP FUNCTION IF EXISTS get_origin_packages_unique_for_origin_v5(text, bigint, bigint, origin_package_visibility[]);
DROP FUNCTION IF EXISTS insert_origin_package_v5(bigint, bigint, text, text, text, text, text, text, text[], text[], integer[], origin_package_visibility);
DROP FUNCTION IF EXISTS add_audit_package_entry_v3(text, text, text, origin_package_operation, package_channel_trigger, bigint, text);
DROP FUNCTION IF EXISTS promote_origin_package_v3(text, text, text);
DROP FUNCTION IF EXISTS demote_origin_package_v3(text, text, text);
DROP FUNCTION IF EXISTS update_package_visibility_in_bulk_v2(origin_package_visibility, bigint[]);
DROP FUNCTION IF EXISTS update_origin_package_v2(bigint, bigint, text, text, text, text, text, text, text[], text[], integer[], origin_package_visibility);
DROP FUNCTION IF EXISTS get_origin_v1(text);
DROP FUNCTION IF EXISTS insert_origin_v3(text, bigint, text, origin_package_visibility);
DROP FUNCTION IF EXISTS update_origin_v2(text, origin_package_visibility);
DROP FUNCTION IF EXISTS my_origins_with_stats_v2(bigint);
DROP FUNCTION IF EXISTS get_origin_channel_package_latest_v7(text, text, text[], text, origin_package_visibility[]);
DROP FUNCTION IF EXISTS get_origin_channel_packages_for_channel_v5(text, text, text[], origin_package_visibility[], bigint, bigint);
DROP FUNCTION IF EXISTS get_origin_package_latest_v7(text[], text, origin_package_visibility[]);
DROP FUNCTION IF EXISTS get_origin_package_platforms_for_package_v6(text[], origin_package_visibility[]);
DROP FUNCTION IF EXISTS get_origin_packages_for_origin_distinct_v6(text[], bigint, bigint, origin_package_visibility[]);
DROP FUNCTION IF EXISTS get_origin_packages_for_origin_v7(text[], bigint, bigint, origin_package_visibility[]);
DROP FUNCTION IF EXISTS get_origin_channel_package_latest_v8(text, text, text[], text, origin_package_visibility[]);
DROP FUNCTION IF EXISTS add_audit_package_group_entry_v2(text, text, bigint[], origin_package_operation, package_channel_trigger, bigint, text, bigint);
DROP FUNCTION IF EXISTS insert_origin_project_v6(text, text, text, text, text, bigint, bigint, origin_package_visibility, boolean);
DROP FUNCTION IF EXISTS update_origin_project_v5(bigint, bigint, text, text, text, text, bigint, bigint, origin_package_visibility, boolean);
DROP FUNCTION IF EXISTS get_origin_channel_v1(text, text);
DROP FUNCTION IF EXISTS get_origin_package_v4(text, text);
DROP FUNCTION IF EXISTS insert_origin_channel_v1(bigint, bigint, text);
DROP FUNCTION IF EXISTS insert_origin_member_v1(bigint, text, bigint, text);
DROP FUNCTION IF EXISTS promote_origin_package_v1(bigint, bigint);
DROP VIEW IF EXISTS origins_with_private_encryption_key_full_name_v1;
DROP VIEW IF EXISTS origins_with_secret_key_full_name_v2;
