version: '3'
services:
  builder-memcache:
    image: memcached:latest
    container_name: builder-memcached
    ports:
      - "11211:11211"
    networks:
      - backend
  builder-minio:
    image: quay.io/minio/minio:latest
    container_name: builder-minio
    environment:
      - MINIO_ROOT_USER=root_Admin
      - MINIO_ROOT_PASSWORD=123456789qax
    volumes:
      - ./tmp/data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data
    networks:
      - backend
  builder-datastore:
    image: postgres:11.4
    container_name: builder-datastore
    environment:
      - POSTGRES_DB=builder
      - POSTGRES_USER=hab
      - POSTGRES_PASSWORD=passwrd1298
      - PG_MAX_CONNECTIONS=100
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    networks:
      - backend
  builder-api:
    build: .
    container_name: builder-api
    ports:
      - "9636:9636"
    environment:
      - POSTGRES_HOST=builder-datastore
      - POSTGRES_PORT=5432
      - POSTGRES_DB=builder
      - POSTGRES_USER=hab
      - POSTGRES_PASSWORD=passwrd1298
      - POSTGRES_SSLMODE=prefer
      - MINIO_ACCESS_KEY=root_Admin
      - MINIO_SECRET_KEY=123456789qax
      - MINIO_ENDPOINT=http://localhost:9000
      - MINIO_BUCKET=test
      - RUST_LOG=debug
    networks:
      - backend
    depends_on:
      builder-memcache:
        condition: service_started
      builder-datastore:
        condition: service_started
      builder-minio:
        condition: service_started
    volumes:
      - ./tmp/tokens:/tokens
networks:
  backend:
    driver: bridge
