#!/bin/sh

exec 2>&1

export AWS_ACCESS_KEY_ID="{{cfg.key_id}}"
export AWS_SECRET_ACCESS_KEY="{{cfg.secret_key}}"

{{ #if cfg.use_ssl }}
MINIO_ENDPOINT="--endpoint-url https://localhost:9000 --no-verify-ssl"
{{else ~}}
MINIO_ENDPOINT="--endpoint-url http://localhost:9000"
{{ /if }}

if {{pkgPathFor "core/aws-cli"}}/bin/aws $MINIO_ENDPOINT s3api list-buckets | grep "{{cfg.bucket_name}}" > /dev/null; then
  echo "Minio already configured"
else
  echo "Creating bucket in Minio"
  {{pkgPathFor "core/aws-cli"}}/bin/aws  $MINIO_ENDPOINT s3api create-bucket --bucket "{{cfg.bucket_name}}"
fi