#!/bin/sh

exec 2>&1

export MINIO_ACCESS_KEY="{{cfg.key_id}}"
export MINIO_SECRET_KEY="{{cfg.secret_key}}"

{{#if cfg.ssl_cert_pw}}
    export MINIO_CERT_PASSWD="{{cfg.ssl_cert_pw}}"
{{/if ~}}

exec minio server \
--config-dir "{{pkg.svc_config_path}}" \
"{{pkg.svc_data_path}}"

