format_version = 1
file_descriptor = "Packages needed to run an instance of Builder"

[[x86_64-linux]]
channel = "acceptance"
packages = [
  # Supervisor and prerequisites
  "chef/hab-launcher",
  "chef/hab",
  "chef/hab-sup",
]

[[x86_64-linux]]
channel = "LTS-2024"
packages = [
  # Builder services
  "habitat/builder-api",
  "habitat/builder-api-proxy",
  "habitat/builder-memcached",
]
