[http]
handler_count = 10
listen = "0.0.0.0"
port = 9636

[api]
features_enabled = "nativepackages"
targets = ["x86_64-linux", "x86_64-linux-kernel2", "x86_64-windows"]
build_on_upload = false
saas_bldr_url = "https://bldr.habitat.sh"
key_path = "/app/keys"

[s3]
backend = "minio"
# endpoint = "http://localhost:9000"
# key_id = "root_Admin"
# secret_key = "123456789qax"
# bucket_name = "test"

[memcache]
ttl = 15
[[memcache.hosts]]
# host = "builder-memcache"
# port = 11211

[datastore]
# host = "localhost"
# port = 5432
ssl_mode = "prefer"
# user = "hab"
# password = ""
# database = "builder"

[provision]
auto_provision_account = true
token_path = "/tokens"
origins = ["core", "chef", "chef-platform"]
channels = ["stable"]
