max_connections = 200
max_locks_per_transaction = 128
dynamic_shared_memory_type = 'posix'
port = 5433 # To avoid conflict with travis' own postgres instance

[superuser]
name = 'hab'
password = 'hab'
