#!/bin/bash

exec 2>&1

export JAVA_HOME="{{pkgPathFor "core/corretto11"}}"
export KAFKA_LOG4J_OPTS="-Dlog4j.configuration=file:{{pkg.svc_config_path}}/log4j.properties"
export EXTRA_ARGS="-name kafkaServer"

# Kafka listens on port 9092 by default
if ! netstat -tulpn | grep 9092 &>/dev/null; then
  exec {{pkg.path}}/bin/kafka-server-start.sh "{{pkg.svc_config_path}}/server.properties"
fi
